### ISSUE TITLE
10x higher startup time if debug info is not stripped

### ISSUE THREAD

**Issue by Shnatsel** [ronnychevalier/cargo-multivers#2]
I've measured the startup time of Cargo's default "hello world" program on `x86_64-unknown-linux-gnu` target.  If I run `cargo multivers` and with the default configuration, I'm seeing the startup time of 68ms.

Adding the following lines to `Cargo.toml` brings it down to 9ms:

```toml
[profile.release]
strip = true
```
This translates into the [`-C debuginfo` compiler flag](https://doc.rust-lang.org/rustc/codegen-options/index.html#debuginfo) and instructs the compiler to remove the debug info, which makes up the vast majority of the size of the binary.

I don't think the original debug info would be helpful for an executable that's reconstructed through binary diffing (although I haven't tested it). Perhaps always passing this flag would be a good idea to cut down on binary size and therefore startup time?

If the debug info is still useful in binaries compiled with multivers, I think this trick should not be the default but should be documented in the README.

**Comment by Shnatsel** [comment]
Also, thanks for crating `cargo multivers`! I think it's a fresh and exciting way to deal with CPU features.

**Comment by ronnychevalier** [comment]
> I don't think the original debug info would be helpful for an executable that's reconstructed through binary diffing (although I haven't tested it). Perhaps always passing this flag would be a good idea to cut down on binary size and therefore startup time?
> 

In the tests, I [stripped the binaries](https://github.com/ronnychevalier/cargo-multivers/blob/3e517702dae67946e4c931dcde1ff2c8fdb77072/tests/test-argv/Cargo.toml#L10) for this reason, but I have not documented it.
But I agree, `cargo multivers` should disable it by default.

> Also, thanks for crating cargo multivers! I think it's a fresh and exciting way to deal with CPU features.

Thanks!

**Comment by ronnychevalier** [comment]
> This translates into the [-C debuginfo compiler flag](https://doc.rust-lang.org/rustc/codegen-options/index.html#debuginfo) and instructs the compiler to remove the debug info, which makes up the vast majority of the size of the binary.

The strip configuration field in `Cargo.toml` translates to the [`-C strip` compiler flag](https://doc.rust-lang.org/rustc/codegen-options/index.html#strip). `debuginfo` is already disabled by default on the `release` profile.

**Comment by Shnatsel** [comment]
> `debuginfo` is already disabled by default on the release profile.

That is demonstrably not the case. Try using `cargo build --release` with and without `strip = true` in `Cargo.toml`; you will see a huge difference in binary size.

**Comment by Shnatsel** [comment]
Oh, do you mean `cargo multivers --release`? I did not try that.

**Comment by ronnychevalier** [comment]
I'm not sure what's the right fix for this should be.

We could add `-C strip=symbols` by default, and add a config field `keep-debuginfo` in `[package.metadata.multivers]` to disable this behavior?
But if we add it by default, one could argue that we should also enable by default things like `lto=thin` or `panic=abort`. In that case, we would need to also add additional settings in `[package.metadata.multivers]` to disable these behaviors. In the end, it would be re-implementing and duplicating the profile settings in `[package.metadata.multivers]` and I'm not sure this is the right solution.

Until we figure out a proper solution, or until I'm convinced the solution above is the right fix, I have documented (f1d609f077074ece1a89d3bd9001dc4e9125e1a3) that enabling such options is recommended.

**Comment by Shnatsel** [comment]
Thank you! I'm going to go ahead and close this issue, and perhaps open another one for a different default later.
