### ISSUE TITLE
cargo multivers not working properly

### ISSUE THREAD

**Issue by PaulDotSH** [ronnychevalier/cargo-multivers#5]
Compiling 39 versions compressed into a runner
Error: Cargo command failed: The cargo subcommand returned an error.
error: current package believes it's in a workspace when it's not:
current:   /home/admin/tmp/surrealdb/target/cargo-multivers/package-runner/Cargo.toml
workspace: /home/admin/tmp/surrealdb/Cargo.toml

this may be fixable by adding `target/cargo-multivers/package-runner` to the `workspace.members` array of the manifest located at: /home/admin/tmp/surrealdb/Cargo.toml
Alternatively, to keep it out of the workspace, add the package to the `workspace.exclude` array, or add an empty `[workspace]` table to the package's manifest.

I got this error 2 times, adding `target/cargo-multivers/package-runner` to the `workspace.members` in /home/admin/tmp/surrealdb/Cargo.toml didn't fix the problem. How can I fix this?

**Comment by ronnychevalier** [comment]
You are right something was missing to make it build a binary from a workspace. It is now fixed in the version 0.7.0.

**Comment by PaulDotSH** [comment]
> You are right something was missing to make it build a binary from a workspace. It is now fixed in the version 0.7.0.

The issue was however somehow fixed by adding `exclude = ["target/cargo-multivers/package-runner/Cargo.toml"]`
That's why I closed the issue, it is awesome if it now works without this "workaround", I cannot test it yet however since I'm building something with the fixed workaround and it will take more than a few hours, I would gladly test if after though.
